### ISSUE TITLE
Android Support?

### ISSUE THREAD

**Issue by ericraio** [wynnej1983/react-native-appirater#1]
Great module!

Thoughts on adding this lib?
https://github.com/drewjw81/appirater-android

**Comment by wynnej1983** [comment]
@ericraio yes id like to add it. if u would like to do it first ill happily accept PR ;) its just a matter of adding a wrapper for react-native.

**Comment by wynnej1983** [comment]
@ericraio just pushed android support based on https://github.com/drewjw81/appirater-android repo and merged into master.
I have not tested it at all so if you have time can you check it out? thx

**Comment by ericraio** [comment]
@wynnej1983 nice work! I'll be installing this tonight or tomorrow and i'll test it out.

Thanks for adding this.

**Comment by ericraio** [comment]
@wynnej1983 I couldn't get this library to build for android. I don't have a lot of experience in java so I don't know why it's complaining about this.

```
node_modules/react-native-appirater/android/src/main/java/com/wynnej1983/appirater/RNAppiraterModule.java:261: error: cannot find symbol
        Button noButton = (Button)layout.findViewById(R.id.love_dialog_no);
                                                          ^
  symbol:   variable love_dialog_no
  location: class id
4 errors
:RNAppirater:compileReleaseJavaWithJavac FAILED
```

**Comment by wynnej1983** [comment]
@ericraio
So I may have missed a few necessary files when copying over from this repro https://github.com/drewjw81/appirater-android

Seems error is missing resource for a like dialog component with yes/no button resources. I'm not at desktop right now but if I was I'd do a grep search in drewjw81 project for the missing resources.

**Comment by ericraio** [comment]
@wynnej1983 yeah I was banging my head last night, I was dragging over the resources but couldn't get the compiler to pick up the files and load them in. :(

**Comment by ericraio** [comment]
@wynnej1983 wow man, awesome work. It compiles. Couldn't get the dialog to prompt but seriously thanks for the fixes so far!

**Comment by wynnej1983** [comment]
👍

**Comment by ericraio** [comment]
@wynnej1983 what needs to be done for it to prompt on android?

**Comment by wynnej1983** [comment]
@ericraio ok so i havent tested this yet but i think setting `test_mode` to true will show the prompt everytime on android.
→ https://github.com/wynnej1983/react-native-appirater/blob/master/android/src/main/res/values/appirater-settings.xml#L15

if this works maybe you can update the README to reflect this ; )
let me know if it works, thx

**Comment by wynnej1983** [comment]
@ericraio 
note that you will need to make this setting change in the **your** project **after** following the step explained below in the README
↓↓↓

### Usage (Android)

Copy the /res/values/appirater-settings.xml from the AppiraterAndroid library in to your projects /res/values/ folder and adjust the settings to your preference.

**Comment by wynnej1983** [comment]
closing this issue

**Comment by ericraio** [comment]
@wynnej1983 thanks for the support. I'll be working on an Android version again in a week or 2. Want me add documentation and feedback?

**Comment by wynnej1983** [comment]
@ericraio it would be great if you could add documentation. Anything is appreciated. Thanks!
