### ISSUE TITLE
not available on npm registry

### ISSUE THREAD

**Issue by ericraio** [wynnej1983/react-native-appirater#4]
wasn't able to download it because it wasn't published to NPM

https://www.npmjs.com/package/react-native-appirater

**Comment by ericraio** [comment]
@wynnej1983 I submitted your package to react.parts and js.coach for others to find it but the owner of the sites wasn't able to upload it because it's not on NPM :(

**Comment by wynnej1983** [comment]
@ericraio i pushed android support to repro now and published npm module.
ios version looks functional but android just about compiles so it may not even work properly, needs testing..
